// Walford World Cup Syndicate 2026 - Supabase config
const SUPABASE_URL = "https://ndgspyviqtewhfuzlted.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZ3NweXZpcXRld2hmdXpsdGVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyMzIwNTYsImV4cCI6MjA5NjgwODA1Nn0.f1oipHwBmCrIxCeVqCy83XfLSqXhpGT541AbK6LmUMQ";
