create table if not exists fixtures (
  id bigint generated by default as identity primary key,
  match_date date not null,
  kickoff_gmt time not null,
  team_a text not null,
  team_b text not null,
  created_at timestamptz default now()
);

alter table fixtures enable row level security;

create policy "Public can read fixtures"
on fixtures
for select
to anon, authenticated
using (true);

-- Later, after creating your admin login, add an insert policy for authenticated users:
-- create policy "Authenticated can insert fixtures"
-- on fixtures
-- for insert
-- to authenticated
-- with check (true);
